import { Lawyer, Demand, Contract, Post, CorrespondentRequest, Review, Plan } from '@/types'

export const mockLawyers: Lawyer[] = [
  {
    id: 'l1',
    name: 'Dr. Carlos Mendes',
    email: 'carlos@example.com',
    role: 'lawyer',
    avatar: 'https://i.pravatar.cc/150?img=3',
    oabNumber: '123456',
    oabState: 'SP',
    status: 'verified',
    bio: 'Advogado especialista em Direito Trabalhista com mais de 15 anos de experiência.',
    specialties: ['Direito Trabalhista', 'Direito Previdenciário'],
    uf: 'SP',
    city: 'São Paulo',
    rating: 4.8,
    reviewCount: 47,
    plan: 'pro',
    isVisible: true,
    createdAt: '2022-01-15T00:00:00Z',
  },
  {
    id: 'l2',
    name: 'Dra. Ana Lima',
    email: 'ana@example.com',
    role: 'lawyer',
    avatar: 'https://i.pravatar.cc/150?img=5',
    oabNumber: '654321',
    oabState: 'RJ',
    status: 'verified',
    bio: 'Especialista em Direito de Família e Sucessões.',
    specialties: ['Direito de Família', 'Direito Civil'],
    uf: 'RJ',
    city: 'Rio de Janeiro',
    rating: 4.6,
    reviewCount: 32,
    plan: 'free',
    isVisible: true,
    createdAt: '2022-06-10T00:00:00Z',
  },
  {
    id: 'l3',
    name: 'Dr. Felipe Santos',
    email: 'felipe@example.com',
    role: 'lawyer',
    avatar: 'https://i.pravatar.cc/150?img=7',
    oabNumber: '789012',
    oabState: 'MG',
    status: 'verified',
    bio: 'Advogado tributarista com foco em PMEs e startups.',
    specialties: ['Direito Tributário', 'Direito Empresarial'],
    uf: 'MG',
    city: 'Belo Horizonte',
    rating: 4.9,
    reviewCount: 61,
    plan: 'pro',
    isVisible: true,
    createdAt: '2021-11-20T00:00:00Z',
  },
  {
    id: 'l4',
    name: 'Dra. Juliana Costa',
    email: 'juliana@example.com',
    role: 'lawyer',
    avatar: 'https://i.pravatar.cc/150?img=9',
    oabNumber: '345678',
    oabState: 'BA',
    status: 'pending',
    bio: 'Advogada imobiliária com experiência em contratos e incorporações.',
    specialties: ['Direito Imobiliário', 'Direito Contratual'],
    uf: 'BA',
    city: 'Salvador',
    rating: 0,
    reviewCount: 0,
    plan: 'free',
    isVisible: false,
    createdAt: '2024-01-05T00:00:00Z',
  },
]

export const mockDemands: Demand[] = [
  {
    id: 'd1',
    clientId: 'c1',
    title: 'Preciso de assessoria em rescisão trabalhista',
    description: 'Fui demitido sem justa causa e tenho dúvidas sobre meus direitos e valores a receber.',
    specialty: 'Direito Trabalhista',
    uf: 'SP',
    budget: 500,
    status: 'open',
    proposalsCount: 3,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
  },
  {
    id: 'd2',
    clientId: 'c2',
    title: 'Consultoria para abertura de empresa',
    description: 'Quero abrir uma startup de tecnologia e preciso entender a melhor estrutura societária.',
    specialty: 'Direito Empresarial',
    uf: 'SP',
    budget: 1200,
    status: 'in_progress',
    proposalsCount: 5,
    createdAt: '2024-03-08T14:00:00Z',
    updatedAt: '2024-03-09T08:00:00Z',
  },
  {
    id: 'd3',
    clientId: 'c1',
    title: 'Divórcio consensual',
    description: 'Meu cônjuge e eu decidimos nos divorciar de forma amigável. Precisamos de apoio para os documentos.',
    specialty: 'Direito de Família',
    uf: 'RJ',
    status: 'open',
    proposalsCount: 1,
    createdAt: '2024-03-12T09:00:00Z',
    updatedAt: '2024-03-12T09:00:00Z',
  },
]

export const mockPosts: Post[] = [
  {
    id: 'p1',
    authorId: 'l1',
    author: mockLawyers[0],
    title: '5 direitos do trabalhador que você precisa conhecer',
    content: 'Muitos trabalhadores não sabem que têm direito ao aviso prévio proporcional ao tempo de serviço...',
    tags: ['Direito Trabalhista', 'Dicas'],
    likesCount: 124,
    commentsCount: 18,
    isLiked: false,
    createdAt: '2024-03-14T10:00:00Z',
    updatedAt: '2024-03-14T10:00:00Z',
  },
  {
    id: 'p2',
    authorId: 'l3',
    author: mockLawyers[2],
    title: 'Como reduzir a carga tributária da sua empresa legalmente',
    content: 'O planejamento tributário é uma ferramenta legal que permite às empresas otimizar o pagamento de impostos...',
    tags: ['Direito Tributário', 'Empresas'],
    likesCount: 89,
    commentsCount: 12,
    isLiked: true,
    createdAt: '2024-03-13T08:00:00Z',
    updatedAt: '2024-03-13T08:00:00Z',
  },
  {
    id: 'p3',
    authorId: 'l2',
    author: mockLawyers[1],
    title: 'Guarda compartilhada: o que diz a lei',
    content: 'A guarda compartilhada é a regra no direito brasileiro e visa preservar os laços afetivos da criança...',
    tags: ['Direito de Família', 'Guarda'],
    likesCount: 201,
    commentsCount: 34,
    isLiked: false,
    createdAt: '2024-03-11T15:00:00Z',
    updatedAt: '2024-03-11T15:00:00Z',
  },
]

export const mockContracts: Contract[] = [
  {
    id: 'ct1',
    demandId: 'd2',
    proposalId: 'pr1',
    clientId: 'c2',
    lawyerId: 'l3',
    lawyer: mockLawyers[2],
    price: 1200,
    status: 'active',
    createdAt: '2024-03-09T08:00:00Z',
  },
]

export const mockReviews: Review[] = [
  {
    id: 'r1',
    contractId: 'ct1',
    reviewerId: 'c2',
    lawyerId: 'l1',
    rating: 5,
    comment: 'Excelente profissional! Muito atencioso e competente. Resolveu meu caso rapidamente.',
    isVerified: true,
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'r2',
    contractId: 'ct2',
    reviewerId: 'c3',
    lawyerId: 'l1',
    rating: 4,
    comment: 'Bom trabalho, comunicação clara e objetiva. Recomendo.',
    isVerified: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
]

export const mockCorrespondentRequests: CorrespondentRequest[] = [
  {
    id: 'cr1',
    requesterId: 'l1',
    requester: mockLawyers[0],
    title: 'Audiência trabalhista — Fórum do Brás',
    description: 'Necessito de correspondente para audiência de instrução em reclamação trabalhista.',
    uf: 'SP',
    city: 'São Paulo',
    specialty: 'Direito Trabalhista',
    hearing: '2024-04-15T14:00:00Z',
    deadline: '2024-04-10T23:59:59Z',
    budget: 350,
    status: 'open',
    proposalsCount: 2,
    createdAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'cr2',
    requesterId: 'l3',
    requester: mockLawyers[2],
    title: 'Sustentação oral — TJ-MG',
    description: 'Preciso de advogado habilitado no TJMG para sustentação oral em apelação cível.',
    uf: 'MG',
    city: 'Belo Horizonte',
    specialty: 'Direito Civil',
    hearing: '2024-04-20T10:00:00Z',
    deadline: '2024-04-15T23:59:59Z',
    budget: 600,
    status: 'open',
    proposalsCount: 1,
    createdAt: '2024-03-14T11:00:00Z',
  },
]

export const mockPlans: Plan[] = [
  {
    id: 'plan1',
    name: 'Free',
    slug: 'free',
    priceMonthly: 0,
    priceYearly: 0,
    features: [
      'Perfil público básico',
      'Até 3 propostas/mês',
      'Acesso ao feed',
      'Receber contatos verificados',
    ],
    limits: { proposals: 3, teamMembers: null, analytics: false },
  },
  {
    id: 'plan2',
    name: 'Pro',
    slug: 'pro',
    priceMonthly: 89,
    priceYearly: 799,
    features: [
      'Tudo do Free',
      'Propostas ilimitadas',
      'Dashboard de performance',
      'Destaque na busca',
      'Selo Pro verificado',
      'Módulo de correspondentes',
    ],
    limits: { proposals: null, teamMembers: null, analytics: true },
  },
  {
    id: 'plan3',
    name: 'Escritório',
    slug: 'office',
    priceMonthly: 299,
    priceYearly: 2699,
    features: [
      'Tudo do Pro',
      'Até 15 membros na equipe',
      'BI e relatórios avançados',
      'Agenda compartilhada',
      'Gestão de casos',
      'Suporte prioritário',
    ],
    limits: { proposals: null, teamMembers: 15, analytics: true },
  },
]
